[package]
name = "brig-ir"
version.workspace = true
edition.workspace = true

[dependencies]
brig-common = { path = "../brig-common" }
brig-diagnostic = { path = "../brig-diagnostic" }
brig-ast = { path = "../brig-ast" }
