[workspace]
resolver = "2"
members = [
	"brig-common",
	"brig-diagnostic",
	"brig-ast",
	"brig-lexer",
	"brig-macros",
	"brig-parser",
	"brig",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
