[package]
name = "brig-diagnostic"
version.workspace = true
edition.workspace = true

[dependencies]
brig-common = { path = "../brig-common" }
ariadne = { version = "0.4.1", features = ["auto-color"] }
